// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/jobqueue-grpc/pb/api_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=./internal/jobqueue-grpc/pb/api_grpc.pb.go -destination=./internal/mocks/mock_jobqueue.go
//

// Package mock_pb is a generated GoMock package.
package mock_pb

import (
	context "context"
	reflect "reflect"

	pb "github.com/luisync/Job-Queue/internal/jobqueue-grpc/pb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockJobqueueClient is a mock of JobqueueClient interface.
type MockJobqueueClient struct {
	ctrl     *gomock.Controller
	recorder *MockJobqueueClientMockRecorder
	isgomock struct{}
}

// MockJobqueueClientMockRecorder is the mock recorder for MockJobqueueClient.
type MockJobqueueClientMockRecorder struct {
	mock *MockJobqueueClient
}

// NewMockJobqueueClient creates a new mock instance.
func NewMockJobqueueClient(ctrl *gomock.Controller) *MockJobqueueClient {
	mock := &MockJobqueueClient{ctrl: ctrl}
	mock.recorder = &MockJobqueueClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobqueueClient) EXPECT() *MockJobqueueClientMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobqueueClient) CreateJob(ctx context.Context, in *pb.JobsReq, opts ...grpc.CallOption) (*pb.JobsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateJob", varargs...)
	ret0, _ := ret[0].(*pb.JobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobqueueClientMockRecorder) CreateJob(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobqueueClient)(nil).CreateJob), varargs...)
}

// CreateSession mocks base method.
func (m *MockJobqueueClient) CreateSession(ctx context.Context, in *pb.SessionsReq, opts ...grpc.CallOption) (*pb.SessionsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSession", varargs...)
	ret0, _ := ret[0].(*pb.SessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockJobqueueClientMockRecorder) CreateSession(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockJobqueueClient)(nil).CreateSession), varargs...)
}

// DeteleSessions mocks base method.
func (m *MockJobqueueClient) DeteleSessions(ctx context.Context, in *pb.SessionsReq, opts ...grpc.CallOption) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeteleSessions", varargs...)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeteleSessions indicates an expected call of DeteleSessions.
func (mr *MockJobqueueClientMockRecorder) DeteleSessions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeteleSessions", reflect.TypeOf((*MockJobqueueClient)(nil).DeteleSessions), varargs...)
}

// FindJob mocks base method.
func (m *MockJobqueueClient) FindJob(ctx context.Context, in *pb.FindJobReq, opts ...grpc.CallOption) (*pb.JobsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindJob", varargs...)
	ret0, _ := ret[0].(*pb.JobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJob indicates an expected call of FindJob.
func (mr *MockJobqueueClientMockRecorder) FindJob(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJob", reflect.TypeOf((*MockJobqueueClient)(nil).FindJob), varargs...)
}

// FindLatestJobResult mocks base method.
func (m *MockJobqueueClient) FindLatestJobResult(ctx context.Context, in *pb.JobResultsReq, opts ...grpc.CallOption) (*pb.JobResultsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindLatestJobResult", varargs...)
	ret0, _ := ret[0].(*pb.JobResultsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestJobResult indicates an expected call of FindLatestJobResult.
func (mr *MockJobqueueClientMockRecorder) FindLatestJobResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestJobResult", reflect.TypeOf((*MockJobqueueClient)(nil).FindLatestJobResult), varargs...)
}

// FindSessionByID mocks base method.
func (m *MockJobqueueClient) FindSessionByID(ctx context.Context, in *pb.SessionsReq, opts ...grpc.CallOption) (*pb.SessionsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindSessionByID", varargs...)
	ret0, _ := ret[0].(*pb.SessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionByID indicates an expected call of FindSessionByID.
func (mr *MockJobqueueClientMockRecorder) FindSessionByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionByID", reflect.TypeOf((*MockJobqueueClient)(nil).FindSessionByID), varargs...)
}

// FindSessionsByEmail mocks base method.
func (m *MockJobqueueClient) FindSessionsByEmail(ctx context.Context, in *pb.SessionsReq, opts ...grpc.CallOption) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindSessionsByEmail", varargs...)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionsByEmail indicates an expected call of FindSessionsByEmail.
func (mr *MockJobqueueClientMockRecorder) FindSessionsByEmail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionsByEmail", reflect.TypeOf((*MockJobqueueClient)(nil).FindSessionsByEmail), varargs...)
}

// FindUserByEmail mocks base method.
func (m *MockJobqueueClient) FindUserByEmail(ctx context.Context, in *pb.UsersReq, opts ...grpc.CallOption) (*pb.UsersRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindUserByEmail", varargs...)
	ret0, _ := ret[0].(*pb.UsersRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockJobqueueClientMockRecorder) FindUserByEmail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockJobqueueClient)(nil).FindUserByEmail), varargs...)
}

// ListJobResults mocks base method.
func (m *MockJobqueueClient) ListJobResults(ctx context.Context, in *pb.JobResultsReq, opts ...grpc.CallOption) (*pb.ListJobResultsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListJobResults", varargs...)
	ret0, _ := ret[0].(*pb.ListJobResultsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobResults indicates an expected call of ListJobResults.
func (mr *MockJobqueueClientMockRecorder) ListJobResults(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobResults", reflect.TypeOf((*MockJobqueueClient)(nil).ListJobResults), varargs...)
}

// ListJobs mocks base method.
func (m *MockJobqueueClient) ListJobs(ctx context.Context, in *pb.JobsReq, opts ...grpc.CallOption) (*pb.ListJobsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListJobs", varargs...)
	ret0, _ := ret[0].(*pb.ListJobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobqueueClientMockRecorder) ListJobs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobqueueClient)(nil).ListJobs), varargs...)
}

// Register mocks base method.
func (m *MockJobqueueClient) Register(ctx context.Context, in *pb.UsersReq, opts ...grpc.CallOption) (*pb.UsersRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*pb.UsersRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockJobqueueClientMockRecorder) Register(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockJobqueueClient)(nil).Register), varargs...)
}

// RevokeSessions mocks base method.
func (m *MockJobqueueClient) RevokeSessions(ctx context.Context, in *pb.SessionsReq, opts ...grpc.CallOption) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeSessions", varargs...)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSessions indicates an expected call of RevokeSessions.
func (mr *MockJobqueueClientMockRecorder) RevokeSessions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessions", reflect.TypeOf((*MockJobqueueClient)(nil).RevokeSessions), varargs...)
}

// MockJobqueueServer is a mock of JobqueueServer interface.
type MockJobqueueServer struct {
	ctrl     *gomock.Controller
	recorder *MockJobqueueServerMockRecorder
	isgomock struct{}
}

// MockJobqueueServerMockRecorder is the mock recorder for MockJobqueueServer.
type MockJobqueueServerMockRecorder struct {
	mock *MockJobqueueServer
}

// NewMockJobqueueServer creates a new mock instance.
func NewMockJobqueueServer(ctrl *gomock.Controller) *MockJobqueueServer {
	mock := &MockJobqueueServer{ctrl: ctrl}
	mock.recorder = &MockJobqueueServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobqueueServer) EXPECT() *MockJobqueueServerMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobqueueServer) CreateJob(arg0 context.Context, arg1 *pb.JobsReq) (*pb.JobsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0, arg1)
	ret0, _ := ret[0].(*pb.JobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobqueueServerMockRecorder) CreateJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobqueueServer)(nil).CreateJob), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockJobqueueServer) CreateSession(arg0 context.Context, arg1 *pb.SessionsReq) (*pb.SessionsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(*pb.SessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockJobqueueServerMockRecorder) CreateSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockJobqueueServer)(nil).CreateSession), arg0, arg1)
}

// DeteleSessions mocks base method.
func (m *MockJobqueueServer) DeteleSessions(arg0 context.Context, arg1 *pb.SessionsReq) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeteleSessions", arg0, arg1)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeteleSessions indicates an expected call of DeteleSessions.
func (mr *MockJobqueueServerMockRecorder) DeteleSessions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeteleSessions", reflect.TypeOf((*MockJobqueueServer)(nil).DeteleSessions), arg0, arg1)
}

// FindJob mocks base method.
func (m *MockJobqueueServer) FindJob(arg0 context.Context, arg1 *pb.FindJobReq) (*pb.JobsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJob", arg0, arg1)
	ret0, _ := ret[0].(*pb.JobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJob indicates an expected call of FindJob.
func (mr *MockJobqueueServerMockRecorder) FindJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJob", reflect.TypeOf((*MockJobqueueServer)(nil).FindJob), arg0, arg1)
}

// FindLatestJobResult mocks base method.
func (m *MockJobqueueServer) FindLatestJobResult(arg0 context.Context, arg1 *pb.JobResultsReq) (*pb.JobResultsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestJobResult", arg0, arg1)
	ret0, _ := ret[0].(*pb.JobResultsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestJobResult indicates an expected call of FindLatestJobResult.
func (mr *MockJobqueueServerMockRecorder) FindLatestJobResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestJobResult", reflect.TypeOf((*MockJobqueueServer)(nil).FindLatestJobResult), arg0, arg1)
}

// FindSessionByID mocks base method.
func (m *MockJobqueueServer) FindSessionByID(arg0 context.Context, arg1 *pb.SessionsReq) (*pb.SessionsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionByID", arg0, arg1)
	ret0, _ := ret[0].(*pb.SessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionByID indicates an expected call of FindSessionByID.
func (mr *MockJobqueueServerMockRecorder) FindSessionByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionByID", reflect.TypeOf((*MockJobqueueServer)(nil).FindSessionByID), arg0, arg1)
}

// FindSessionsByEmail mocks base method.
func (m *MockJobqueueServer) FindSessionsByEmail(arg0 context.Context, arg1 *pb.SessionsReq) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionsByEmail", arg0, arg1)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionsByEmail indicates an expected call of FindSessionsByEmail.
func (mr *MockJobqueueServerMockRecorder) FindSessionsByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionsByEmail", reflect.TypeOf((*MockJobqueueServer)(nil).FindSessionsByEmail), arg0, arg1)
}

// FindUserByEmail mocks base method.
func (m *MockJobqueueServer) FindUserByEmail(arg0 context.Context, arg1 *pb.UsersReq) (*pb.UsersRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*pb.UsersRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockJobqueueServerMockRecorder) FindUserByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockJobqueueServer)(nil).FindUserByEmail), arg0, arg1)
}

// ListJobResults mocks base method.
func (m *MockJobqueueServer) ListJobResults(arg0 context.Context, arg1 *pb.JobResultsReq) (*pb.ListJobResultsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobResults", arg0, arg1)
	ret0, _ := ret[0].(*pb.ListJobResultsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobResults indicates an expected call of ListJobResults.
func (mr *MockJobqueueServerMockRecorder) ListJobResults(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobResults", reflect.TypeOf((*MockJobqueueServer)(nil).ListJobResults), arg0, arg1)
}

// ListJobs mocks base method.
func (m *MockJobqueueServer) ListJobs(arg0 context.Context, arg1 *pb.JobsReq) (*pb.ListJobsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0, arg1)
	ret0, _ := ret[0].(*pb.ListJobsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobqueueServerMockRecorder) ListJobs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobqueueServer)(nil).ListJobs), arg0, arg1)
}

// Register mocks base method.
func (m *MockJobqueueServer) Register(arg0 context.Context, arg1 *pb.UsersReq) (*pb.UsersRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*pb.UsersRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockJobqueueServerMockRecorder) Register(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockJobqueueServer)(nil).Register), arg0, arg1)
}

// RevokeSessions mocks base method.
func (m *MockJobqueueServer) RevokeSessions(arg0 context.Context, arg1 *pb.SessionsReq) (*pb.ListSessionsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessions", arg0, arg1)
	ret0, _ := ret[0].(*pb.ListSessionsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSessions indicates an expected call of RevokeSessions.
func (mr *MockJobqueueServerMockRecorder) RevokeSessions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessions", reflect.TypeOf((*MockJobqueueServer)(nil).RevokeSessions), arg0, arg1)
}

// mustEmbedUnimplementedJobqueueServer mocks base method.
func (m *MockJobqueueServer) mustEmbedUnimplementedJobqueueServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedJobqueueServer")
}

// mustEmbedUnimplementedJobqueueServer indicates an expected call of mustEmbedUnimplementedJobqueueServer.
func (mr *MockJobqueueServerMockRecorder) mustEmbedUnimplementedJobqueueServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedJobqueueServer", reflect.TypeOf((*MockJobqueueServer)(nil).mustEmbedUnimplementedJobqueueServer))
}

// MockUnsafeJobqueueServer is a mock of UnsafeJobqueueServer interface.
type MockUnsafeJobqueueServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeJobqueueServerMockRecorder
	isgomock struct{}
}

// MockUnsafeJobqueueServerMockRecorder is the mock recorder for MockUnsafeJobqueueServer.
type MockUnsafeJobqueueServerMockRecorder struct {
	mock *MockUnsafeJobqueueServer
}

// NewMockUnsafeJobqueueServer creates a new mock instance.
func NewMockUnsafeJobqueueServer(ctrl *gomock.Controller) *MockUnsafeJobqueueServer {
	mock := &MockUnsafeJobqueueServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeJobqueueServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeJobqueueServer) EXPECT() *MockUnsafeJobqueueServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedJobqueueServer mocks base method.
func (m *MockUnsafeJobqueueServer) mustEmbedUnimplementedJobqueueServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedJobqueueServer")
}

// mustEmbedUnimplementedJobqueueServer indicates an expected call of mustEmbedUnimplementedJobqueueServer.
func (mr *MockUnsafeJobqueueServerMockRecorder) mustEmbedUnimplementedJobqueueServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedJobqueueServer", reflect.TypeOf((*MockUnsafeJobqueueServer)(nil).mustEmbedUnimplementedJobqueueServer))
}
