// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/token/jwt_maker.go
//
// Generated by this command:
//
//	mockgen -source=./internal/token/jwt_maker.go -destination=./internal/mocks/mock_tokenmaker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	token "github.com/luisync/Job-Queue/internal/token"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenMaker is a mock of TokenMaker interface.
type MockTokenMaker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMakerMockRecorder
	isgomock struct{}
}

// MockTokenMakerMockRecorder is the mock recorder for MockTokenMaker.
type MockTokenMakerMockRecorder struct {
	mock *MockTokenMaker
}

// NewMockTokenMaker creates a new mock instance.
func NewMockTokenMaker(ctrl *gomock.Controller) *MockTokenMaker {
	mock := &MockTokenMaker{ctrl: ctrl}
	mock.recorder = &MockTokenMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenMaker) EXPECT() *MockTokenMakerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockTokenMaker) CreateToken(id pgtype.UUID, email string, duration time.Duration) (string, *token.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", id, email, duration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*token.UserClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockTokenMakerMockRecorder) CreateToken(id, email, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockTokenMaker)(nil).CreateToken), id, email, duration)
}

// VerfifyToken mocks base method.
func (m *MockTokenMaker) VerfifyToken(tokenStr string) (*token.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerfifyToken", tokenStr)
	ret0, _ := ret[0].(*token.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerfifyToken indicates an expected call of VerfifyToken.
func (mr *MockTokenMakerMockRecorder) VerfifyToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerfifyToken", reflect.TypeOf((*MockTokenMaker)(nil).VerfifyToken), tokenStr)
}
