// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobLanguage string

const (
	JobLanguageJavascript JobLanguage = "javascript"
	JobLanguagePython     JobLanguage = "python"
)

func (e *JobLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobLanguage(s)
	case string:
		*e = JobLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for JobLanguage: %T", src)
	}
	return nil
}

type NullJobLanguage struct {
	JobLanguage JobLanguage `json:"job_language"`
	Valid       bool        `json:"valid"` // Valid is true if JobLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.JobLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobLanguage), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	CreatorID    pgtype.UUID        `json:"creator_id"`
	Language     JobLanguage        `json:"language"`
	Dependencies string             `json:"dependencies"`
	Function     string             `json:"function"`
	Status       JobStatus          `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type JobResult struct {
	ID        pgtype.UUID        `json:"id"`
	JobID     pgtype.UUID        `json:"job_id"`
	Output    string             `json:"output"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
