// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findJobByID = `-- name: FindJobByID :one
SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at 
FROM jobs 
WHERE id = $1
`

func (q *Queries) FindJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, findJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at
FROM jobs
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Language,
			&i.Dependencies,
			&i.Function,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
