// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    creator_id, 
    language, 
    dependencies, 
    function
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4
) 
RETURNING id, creator_id, language, dependencies, function, status, updated_at, created_at
`

type CreateJobParams struct {
	CreatorID    pgtype.UUID `json:"creator_id"`
	Language     JobLanguage `json:"language"`
	Dependencies string      `json:"dependencies"`
	Function     string      `json:"function"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CreatorID,
		arg.Language,
		arg.Dependencies,
		arg.Function,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findJobByID = `-- name: FindJobByID :one
SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at 
FROM jobs 
WHERE id = $1
`

func (q *Queries) FindJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, findJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at
FROM jobs
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Language,
			&i.Dependencies,
			&i.Function,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
