// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindJobByID(ctx context.Context, id pgtype.UUID) (Job, error)
	ListJobs(ctx context.Context) ([]Job, error)
}

var _ Querier = (*Queries)(nil)
