// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Jobqueue_ListJobs_FullMethodName            = "/pb.jobqueue/ListJobs"
	Jobqueue_FindJob_FullMethodName             = "/pb.jobqueue/FindJob"
	Jobqueue_CreateJob_FullMethodName           = "/pb.jobqueue/CreateJob"
	Jobqueue_FindUserByEmail_FullMethodName     = "/pb.jobqueue/FindUserByEmail"
	Jobqueue_Register_FullMethodName            = "/pb.jobqueue/Register"
	Jobqueue_FindSessionByID_FullMethodName     = "/pb.jobqueue/FindSessionByID"
	Jobqueue_FindSessionsByEmail_FullMethodName = "/pb.jobqueue/FindSessionsByEmail"
	Jobqueue_RevokeSessions_FullMethodName      = "/pb.jobqueue/RevokeSessions"
	Jobqueue_DeteleSessions_FullMethodName      = "/pb.jobqueue/DeteleSessions"
	Jobqueue_CreateSession_FullMethodName       = "/pb.jobqueue/CreateSession"
)

// JobqueueClient is the client API for Jobqueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobqueueClient interface {
	ListJobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*ListJobsRes, error)
	FindJob(ctx context.Context, in *FindJobReq, opts ...grpc.CallOption) (*JobsRes, error)
	CreateJob(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsRes, error)
	FindUserByEmail(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRes, error)
	Register(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRes, error)
	FindSessionByID(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*SessionsRes, error)
	FindSessionsByEmail(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error)
	RevokeSessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error)
	DeteleSessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error)
	CreateSession(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*SessionsRes, error)
}

type jobqueueClient struct {
	cc grpc.ClientConnInterface
}

func NewJobqueueClient(cc grpc.ClientConnInterface) JobqueueClient {
	return &jobqueueClient{cc}
}

func (c *jobqueueClient) ListJobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*ListJobsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsRes)
	err := c.cc.Invoke(ctx, Jobqueue_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) FindJob(ctx context.Context, in *FindJobReq, opts ...grpc.CallOption) (*JobsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsRes)
	err := c.cc.Invoke(ctx, Jobqueue_FindJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) CreateJob(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsRes)
	err := c.cc.Invoke(ctx, Jobqueue_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) FindUserByEmail(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersRes)
	err := c.cc.Invoke(ctx, Jobqueue_FindUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) Register(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersRes)
	err := c.cc.Invoke(ctx, Jobqueue_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) FindSessionByID(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*SessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsRes)
	err := c.cc.Invoke(ctx, Jobqueue_FindSessionByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) FindSessionsByEmail(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsRes)
	err := c.cc.Invoke(ctx, Jobqueue_FindSessionsByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) RevokeSessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsRes)
	err := c.cc.Invoke(ctx, Jobqueue_RevokeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) DeteleSessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*ListSessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsRes)
	err := c.cc.Invoke(ctx, Jobqueue_DeteleSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobqueueClient) CreateSession(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*SessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsRes)
	err := c.cc.Invoke(ctx, Jobqueue_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobqueueServer is the server API for Jobqueue service.
// All implementations must embed UnimplementedJobqueueServer
// for forward compatibility.
type JobqueueServer interface {
	ListJobs(context.Context, *JobsReq) (*ListJobsRes, error)
	FindJob(context.Context, *FindJobReq) (*JobsRes, error)
	CreateJob(context.Context, *JobsReq) (*JobsRes, error)
	FindUserByEmail(context.Context, *UsersReq) (*UsersRes, error)
	Register(context.Context, *UsersReq) (*UsersRes, error)
	FindSessionByID(context.Context, *SessionsReq) (*SessionsRes, error)
	FindSessionsByEmail(context.Context, *SessionsReq) (*ListSessionsRes, error)
	RevokeSessions(context.Context, *SessionsReq) (*ListSessionsRes, error)
	DeteleSessions(context.Context, *SessionsReq) (*ListSessionsRes, error)
	CreateSession(context.Context, *SessionsReq) (*SessionsRes, error)
	mustEmbedUnimplementedJobqueueServer()
}

// UnimplementedJobqueueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobqueueServer struct{}

func (UnimplementedJobqueueServer) ListJobs(context.Context, *JobsReq) (*ListJobsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedJobqueueServer) FindJob(context.Context, *FindJobReq) (*JobsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FindJob not implemented")
}
func (UnimplementedJobqueueServer) CreateJob(context.Context, *JobsReq) (*JobsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedJobqueueServer) FindUserByEmail(context.Context, *UsersReq) (*UsersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserByEmail not implemented")
}
func (UnimplementedJobqueueServer) Register(context.Context, *UsersReq) (*UsersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedJobqueueServer) FindSessionByID(context.Context, *SessionsReq) (*SessionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSessionByID not implemented")
}
func (UnimplementedJobqueueServer) FindSessionsByEmail(context.Context, *SessionsReq) (*ListSessionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSessionsByEmail not implemented")
}
func (UnimplementedJobqueueServer) RevokeSessions(context.Context, *SessionsReq) (*ListSessionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSessions not implemented")
}
func (UnimplementedJobqueueServer) DeteleSessions(context.Context, *SessionsReq) (*ListSessionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeteleSessions not implemented")
}
func (UnimplementedJobqueueServer) CreateSession(context.Context, *SessionsReq) (*SessionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedJobqueueServer) mustEmbedUnimplementedJobqueueServer() {}
func (UnimplementedJobqueueServer) testEmbeddedByValue()                  {}

// UnsafeJobqueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobqueueServer will
// result in compilation errors.
type UnsafeJobqueueServer interface {
	mustEmbedUnimplementedJobqueueServer()
}

func RegisterJobqueueServer(s grpc.ServiceRegistrar, srv JobqueueServer) {
	// If the following call panics, it indicates UnimplementedJobqueueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Jobqueue_ServiceDesc, srv)
}

func _Jobqueue_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).ListJobs(ctx, req.(*JobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_FindJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).FindJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_FindJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).FindJob(ctx, req.(*FindJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).CreateJob(ctx, req.(*JobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_FindUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).FindUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_FindUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).FindUserByEmail(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).Register(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_FindSessionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).FindSessionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_FindSessionByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).FindSessionByID(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_FindSessionsByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).FindSessionsByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_FindSessionsByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).FindSessionsByEmail(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_RevokeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).RevokeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_RevokeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).RevokeSessions(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_DeteleSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).DeteleSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_DeteleSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).DeteleSessions(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobqueue_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobqueueServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jobqueue_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobqueueServer).CreateSession(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Jobqueue_ServiceDesc is the grpc.ServiceDesc for Jobqueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jobqueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.jobqueue",
	HandlerType: (*JobqueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _Jobqueue_ListJobs_Handler,
		},
		{
			MethodName: "FindJob",
			Handler:    _Jobqueue_FindJob_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Jobqueue_CreateJob_Handler,
		},
		{
			MethodName: "FindUserByEmail",
			Handler:    _Jobqueue_FindUserByEmail_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Jobqueue_Register_Handler,
		},
		{
			MethodName: "FindSessionByID",
			Handler:    _Jobqueue_FindSessionByID_Handler,
		},
		{
			MethodName: "FindSessionsByEmail",
			Handler:    _Jobqueue_FindSessionsByEmail_Handler,
		},
		{
			MethodName: "RevokeSessions",
			Handler:    _Jobqueue_RevokeSessions_Handler,
		},
		{
			MethodName: "DeteleSessions",
			Handler:    _Jobqueue_DeteleSessions_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Jobqueue_CreateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
