// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeteleSessions(ctx context.Context, userEmail string) ([]Session, error)
	FindJobByID(ctx context.Context, arg FindJobByIDParams) (Job, error)
	// Sessions
	FindSessionByID(ctx context.Context, id string) (Session, error)
	FindSessionsByEmail(ctx context.Context, userEmail string) ([]Session, error)
	// Users
	FindUserByEmail(ctx context.Context, email string) (User, error)
	// Jobs
	ListJobs(ctx context.Context, creatorID pgtype.UUID) ([]Job, error)
	RevokeSessions(ctx context.Context, userEmail string) ([]Session, error)
	SchedulerFetchAndLockPendingJobs(ctx context.Context, limit int32) ([]pgtype.UUID, error)
	// Private functions for workers.
	WorkerCreateJobResult(ctx context.Context, arg WorkerCreateJobResultParams) (JobResult, error)
	WorkerFindJobByID(ctx context.Context, id pgtype.UUID) (WorkerFindJobByIDRow, error)
	WorkerUpdateStatus(ctx context.Context, arg WorkerUpdateStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
