// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    creator_id, 
    language, 
    dependencies, 
    function
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4
) 
RETURNING id, creator_id, language, dependencies, function, status, updated_at, created_at
`

type CreateJobParams struct {
	CreatorID    pgtype.UUID `json:"creator_id"`
	Language     JobLanguage `json:"language"`
	Dependencies string      `json:"dependencies"`
	Function     string      `json:"function"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CreatorID,
		arg.Language,
		arg.Dependencies,
		arg.Function,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_email, 
    refresh_token,
    is_revoked,
    expires_at
)
VALUES (
    $1, 
    $2, 
    $3,
    $4,
    $5
) 
RETURNING id, user_email, refresh_token, is_revoked, created_at, expires_at
`

type CreateSessionParams struct {
	ID           string    `json:"id"`
	UserEmail    string    `json:"user_email"`
	RefreshToken string    `json:"refresh_token"`
	IsRevoked    bool      `json:"is_revoked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserEmail,
		arg.RefreshToken,
		arg.IsRevoked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name, 
    last_name, 
    username, 
    password,
    email
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4,
    $5
) 
RETURNING id, first_name, last_name, username, email, password, updated_at, created_at
`

type CreateUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Email     string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deteleSessions = `-- name: DeteleSessions :many
DELETE 
FROM sessions 
WHERE user_email = $1
RETURNING id, user_email, refresh_token, is_revoked, created_at, expires_at
`

func (q *Queries) DeteleSessions(ctx context.Context, userEmail string) ([]Session, error) {
	rows, err := q.db.Query(ctx, deteleSessions, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.RefreshToken,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findJobByID = `-- name: FindJobByID :one
SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at 
FROM jobs 
WHERE 
id = $1
AND 
creator_id = $2
`

type FindJobByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatorID pgtype.UUID `json:"creator_id"`
}

func (q *Queries) FindJobByID(ctx context.Context, arg FindJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, findJobByID, arg.ID, arg.CreatorID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionByID = `-- name: FindSessionByID :one

SELECT id, user_email, refresh_token, is_revoked, created_at, expires_at 
FROM sessions 
WHERE id = $1
`

// Sessions
func (q *Queries) FindSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findSessionsByEmail = `-- name: FindSessionsByEmail :many
SELECT id, user_email, refresh_token, is_revoked, created_at, expires_at 
FROM sessions 
WHERE user_email = $1
`

func (q *Queries) FindSessionsByEmail(ctx context.Context, userEmail string) ([]Session, error) {
	rows, err := q.db.Query(ctx, findSessionsByEmail, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.RefreshToken,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT id, first_name, last_name, username, email, password, updated_at, created_at 
FROM users 
WHERE email = $1
`

// Users
func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many

SELECT id, creator_id, language, dependencies, function, status, updated_at, created_at
FROM jobs 
WHERE creator_id = $1
`

// Jobs
func (q *Queries) ListJobs(ctx context.Context, creatorID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Language,
			&i.Dependencies,
			&i.Function,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessions = `-- name: RevokeSessions :many
UPDATE sessions 
SET is_revoked=true
WHERE user_email = $1
RETURNING id, user_email, refresh_token, is_revoked, created_at, expires_at
`

func (q *Queries) RevokeSessions(ctx context.Context, userEmail string) ([]Session, error) {
	rows, err := q.db.Query(ctx, revokeSessions, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.RefreshToken,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerFetchAndLockPendingJobs = `-- name: SchedulerFetchAndLockPendingJobs :many
UPDATE jobs
SET status = 'running'
WHERE id IN (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
    ORDER BY created_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id
`

func (q *Queries) SchedulerFetchAndLockPendingJobs(ctx context.Context, limit int32) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, schedulerFetchAndLockPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workerCreateJobResult = `-- name: WorkerCreateJobResult :one

INSERT INTO job_results (
    job_id, 
    output
)
VALUES (
    $1, 
    $2
) 
RETURNING id, job_id, output, created_at
`

type WorkerCreateJobResultParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	Output string      `json:"output"`
}

// Private functions for workers.
func (q *Queries) WorkerCreateJobResult(ctx context.Context, arg WorkerCreateJobResultParams) (JobResult, error) {
	row := q.db.QueryRow(ctx, workerCreateJobResult, arg.JobID, arg.Output)
	var i JobResult
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Output,
		&i.CreatedAt,
	)
	return i, err
}

const workerFindJobByID = `-- name: WorkerFindJobByID :one
SELECT dependencies, language, function
FROM jobs 
WHERE id = $1
`

type WorkerFindJobByIDRow struct {
	Dependencies string      `json:"dependencies"`
	Language     JobLanguage `json:"language"`
	Function     string      `json:"function"`
}

func (q *Queries) WorkerFindJobByID(ctx context.Context, id pgtype.UUID) (WorkerFindJobByIDRow, error) {
	row := q.db.QueryRow(ctx, workerFindJobByID, id)
	var i WorkerFindJobByIDRow
	err := row.Scan(&i.Dependencies, &i.Language, &i.Function)
	return i, err
}

const workerUpdateStatus = `-- name: WorkerUpdateStatus :one
UPDATE jobs 
SET status=$1
WHERE id = $2
RETURNING id, creator_id, language, dependencies, function, status, updated_at, created_at
`

type WorkerUpdateStatusParams struct {
	Status JobStatus   `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) WorkerUpdateStatus(ctx context.Context, arg WorkerUpdateStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, workerUpdateStatus, arg.Status, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Language,
		&i.Dependencies,
		&i.Function,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
